if(WIN32)
    message(STATUS "Set MinGW Makefiles generator")
    set(CMAKE_GENERATOR "MinGW Makefiles" CACHE INTERNAL "" FORCE)
elseif (UNIX)
    message(STATUS "Set Unix Makefiles generator")
    set(CMAKE_GENERATOR "Unix Makefiles" CACHE INTERNAL "" FORCE)
else()
    message(FATAL_ERROR "Unable to find makefiles generator")
endif()